---
name: C++ CMake Build

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "cpp-algorithm/**"
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y ninja-build

      - name: Setup vcpkg
        working-directory: /usr/local/share/vcpkg
        run: |
          git fetch --all
          git reset --hard origin/master
          ./bootstrap-vcpkg.sh

      - name: Install packages
        working-directory: /usr/local/bin
        run: ./vcpkg install gsl:x64-linux gtest:x64-linux benchmark:x64-linux fmt:x64-linux

      - name: Configure CMake
        run: cmake --preset linux-release -S ${{github.workspace}}/cpp-algorithm -B ${{github.workspace}}/cpp-algorithm/out/build/linux-x64-release

      - name: Build
        working-directory: ${{github.workspace}}/cpp-algorithm/out/build/linux-x64-release
        run: cmake --build . --config ${{env.BUILD_TYPE}} --target all --parallel 6

      - name: Test
        working-directory: ${{github.workspace}}/cpp-algorithm/out/build/linux-x64-release
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
