---
name: C++ CI with CMake

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "cpp-algorithm/**"
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y ninja-build

      - name: Setup vcpkg
        working-directory: /usr/local/share
        run: |
          rm -rf vcpkg
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh

      - name: Install packages
        working-directory: /usr/local/bin
        run: ./vcpkg install gsl:x64-linux gtest:x64-linux benchmark:x64-linux fmt:x64-linux

      - name: Configure CMake
        run: cmake -G Ninja -DCMAKE_C_COMPILER="gcc-10" -DCMAKE_CXX_COMPILER="g++-10" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE="/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_MAKE_PROGRAM="/usr/bin/ninja" -S ${{github.workspace}}/cpp-algorithm -B ${{github.workspace}}/cpp-algorithm/out/build/linux-x64-release

      - name: Build
        run: cmake --build ${{github.workspace}}/cpp-algorithm/out/build/linux-x64-release --config ${{env.BUILD_TYPE}} --target all --parallel 6

      - name: Test
        working-directory: ${{github.workspace}}/cpp-algorithm/out/build/linux-x64-release
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
