---
name: C++ CMake Test

on:
  # every day-of-month 1st at 00:00 UTC
  schedule:
    # prettier-ignore
    - cron: '0 0 1 * *'
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  check-links:
    uses: ./.github/workflows/link-check.yml

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set variables
        run: |
          echo "BUILD_TYPE_LOWERCASE=$(echo ${BUILD_TYPE} | tr '[:upper:]' '[:lower:]')" >> ${GITHUB_ENV}

      - name: Install dependencies
        run: |
          sudo apt install -y ninja-build

      - name: Setup vcpkg
        working-directory: /usr/local/share/vcpkg
        run: |
          git fetch --all
          git reset --hard origin/master
          ./bootstrap-vcpkg.sh

      - name: Install packages
        working-directory: /usr/local/bin
        run: ./vcpkg install gsl:x64-linux gtest:x64-linux benchmark:x64-linux fmt:x64-linux

      - name: Configure CMake
        working-directory: ${{github.workspace}}/cpp-algorithm
        run: make configure

      - name: Build
        working-directory: ${{github.workspace}}/cpp-algorithm
        run: make build

      - name: Test
        working-directory: ${{github.workspace}}/cpp-algorithm
        run: make test
