---
name: Go Test

on:
  # every day-of-month 1st at 00:00 UTC
  schedule:
    # prettier-ignore
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  check-links:
    uses: ./.github/workflows/link-check.yml

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          # prettier-ignore
          go-version: '1.22'
          cache: true
          cache-dependency-path: '**/go.sum'

      - name: Download dependencies
        working-directory: ${{github.workspace}}/go-algorithm
        run: make module

      - name: Test
        working-directory: ${{github.workspace}}/go-algorithm
        run: make test
