---
name: Go Test

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'go-algorithm/**'
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          # prettier-ignore
          go-version: '1.22'

      - name: Test
        working-directory: ${{github.workspace}}/go-algorithm
        run: make
