---
name: Java Gradle Test

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'java-algorithm/**'
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Test
        working-directory: ${{github.workspace}}/java-algorithm
        run: gradle test
