---
name: Java Gradle Test

on:
  # at 08:00 on day-of-month 1
  schedule:
    # prettier-ignore
    - cron: '0 8 1 * *'
  workflow_dispatch:

jobs:
  check-links:
    uses: ./.github/workflows/link-check.yml

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          # prettier-ignore
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Test
        working-directory: ${{github.workspace}}/java-algorithm
        run: gradle test
