---
name: Python Poetry Test

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "python-algorithm/**"
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: ${{github.workspace}}/python-algorithm
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with test

      - name: Test
        working-directory: ${{github.workspace}}/python-algorithm
        run: poetry run pytest
