---
name: Python Poetry Test

on:
  # every day-of-month 1st at 00:00 UTC
  schedule:
    # prettier-ignore
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  check-links:
    uses: ./.github/workflows/link-check.yml

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          # prettier-ignore
          python-version: '3.12'

      - name: Install dependencies
        working-directory: ${{github.workspace}}/python-algorithm
        run: |
          pip install poetry
          poetry install --with test

      - name: Test
        working-directory: ${{github.workspace}}/python-algorithm
        run: poetry run pytest
